### ISSUE TITLE
Edges are not represented well across both graphs

### ISSUE THREAD

**Issue by hallfox** [hallfox/AlgoProject#14]
A unified Edge type needs to be defined. I suggest a pair<int vertexId, double weight>.

**Comment by hallfox** [comment]
Instead we'll use a struct since that just makes more sense.

**Comment by hallfox** [comment]
We now have an edge struct, but it conflicts with DenseGraph's Edge. Armond, can you change your graph to use the Edge used in Edge.h? It looks like all you'd have to do is a search and replace.

**Comment by Astjust1** [comment]
Yeah Ill get it done tomorrow

On Saturday, May 2, 2015, Taylor notifications@github.com wrote:

> We now have an edge struct, but it conflicts with DenseGraph's Edge.
> Armond, can you change your graph to use the Edge used in Edge.h? It looks
> like all you'd have to do is a search and replace.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hallfox/AlgoProject/issues/14#issuecomment-98418524.

## 
- Armond St.Juste

**Comment by Astjust1** [comment]
Added all the fixes. It still won't link for me so if you can test it and
let me know if there are any errors I need to fix that would be great.

**Comment by hallfox** [comment]
Will do. I'll test it when I get the chance.
